### ISSUE TITLE
Fehler in slides_2_daten

### ISSUE THREAD

**Issue by annaheinzl** [skasberger/datenanalyse-ss18#2]
Fehler auf Folie 41. 
Beim Datum statt der Dimension "spatial" gehört "temporal".

**Comment by skasberger** [comment]
Resolved with commit https://github.com/skasberger/datenanalyse-ss18/commit/9559813896168b47643cf9de81f16749349bbdcd.

thanks for the issue!

**Comment by skasberger** [comment]
Resolved with commit https://github.com/skasberger/datenanalyse-ss18/commit/9559813896168b47643cf9de81f16749349bbdcd.

thanks for the issue!
